### ISSUE TITLE
Any chance, or point, of reviving this?

### ISSUE THREAD

**Issue by reppolice** [cyberflohr/mt4j#3]
I had to hunt at OpenJDK for a 32 bit version of Java 9, looks like MQL4 changed ever so slightly since this project was published, and certainly the JVM options changed, which probably explains why I do not get the EA activation dialog upon attaching to a chart. Has the project somewhat been superseded though?

**Comment by cyberflohr** [comment]
I'll try it out but it will take a few days ...:-)

**Comment by cyberflohr** [comment]
I've updated a few parts of the sample code to work with:

Visual Studio 2017
MT 4 Build 1090
Windows SDK 10
Open JDK 9 (32 bit)

**Comment by luded** [comment]
many thanks indeed. :)

**Comment by reppolice** [comment]
Haven't tested it yet, but it should be the next big thing :) Thanks!
